// Generated by CoffeeScript 1.7.1
(function() {
  $(document).ready(function() {
    var setupInput;
    setupInput = function(type, value) {
      return $("<input type='" + type + "' value='" + value + "' />");
    };
    test("Name Input Test", (function(_this) {
      return function() {
        equal(setupInput('text', 'John Doe').isValidAlphaNumericInput(), true, "'John Doe' is Valid!");
        equal(setupInput('text', 'UPPERMAN').isValidAlphaNumericInput(), true, "'UPPERMAN' is Valid!");
        equal(setupInput('text', 'lowerman').isValidAlphaNumericInput(), true, "'lowerman' is Valid!");
        equal(setupInput('text', '').isValidAlphaNumericInput(), false, "'' is not a valid name.");
        equal(setupInput('text', 'Ke$ha').isValidAlphaNumericInput(), false, "'Ke$ha' is not a valid name.");
        equal(setupInput('text', '!@#$%^&*()').isValidAlphaNumericInput(), false, "'!@#$%^&*()' is not a valid name.");
        return equal(setupInput('text', '<a href="http://www.google.com>BadLink</a>"').isValidAlphaNumericInput(), false, "html is not a valid name.");
      };
    })(this));
    return test("Email input Test", (function(_this) {
      return function() {
        equal(setupInput('email', 'John@email.com').isValidEmailInput(), true, "'John@email.com' is Valid!");
        equal(setupInput('email', '123Joe@email.com').isValidEmailInput(), true, "'123Joe@email.com' is Valid!");
        equal(setupInput('email', 'John doe@email.com').isValidEmailInput(), false, "'John doe@email.com' is Invalid!");
        equal(setupInput('email', 'John@').isValidEmailInput(), false, "'John@' is Invalid!");
        equal(setupInput('email', 'John.com').isValidEmailInput(), false, "'John.com' is Invalid!");
        equal(setupInput('email', '@.com').isValidEmailInput(), false, "'@.com' is Invalid!");
        return equal(setupInput('email', '@doe.com').isValidEmailInput(), false, "'@doe.com' is Invalid!");
      };
    })(this));
  });

}).call(this);
