// Generated by CoffeeScript 1.7.1
(function() {
  $(document).ready(function() {
    var setupInput;
    setupInput = function(type, value) {
      return $("<input type='" + type + "' value='" + value + "' />");
    };
    return test("Name Input Test", (function(_this) {
      return function() {
        equal(setupInput('text', 'John Doe').isValidAlphaNumericInput(), true, "'John Doe' is Valid!");
        equal(setupInput('text', 'UPPERMAN').isValidAlphaNumericInput(), true, "'UPPERMAN' is Valid!");
        equal(setupInput('text', 'lowerman').isValidAlphaNumericInput(), true, "'lowerman' is Valid!");
        equal(setupInput('text', '').isValidAlphaNumericInput(), false, "'' is not a valid name.");
        equal(setupInput('text', 'Ke$ha').isValidAlphaNumericInput(), false, "'Ke$ha' is not a valid name.");
        equal(setupInput('text', '!@#$%^&*()').isValidAlphaNumericInput(), false, "'!@#$%^&*()' is not a valid name.");
        return equal(setupInput('text', '<a href="http://www.google.com>BadLink</a>"').isValidAlphaNumericInput(), false, "html is not a valid name.");
      };
    })(this));
  });

}).call(this);
