// Generated by CoffeeScript 1.7.1
(function() {
  var $;

  $ = jQuery;

  $.fn.isValidAlphaNumericInput = function() {
    var allowedPattern, value;
    allowedPattern = /^[a-zA-z0-9\s]+$/i;
    value = $(this).val().trim();
    return allowedPattern.test(value);
  };

  $.fn.isValidEmailInput = function() {
    var allowedPattern, value;
    allowedPattern = /^[\w\-\_\.\d]+@\w+.\w{3}$/;
    value = $(this).val().trim();
    return allowedPattern.test(value);
  };

  $.fn.isValidPhoneInput = function() {
    var allowedPattern, isAllDigits, isDelemited, value, _ref;
    allowedPattern = /^[\d\s\.\-\(\)]+$/;
    isAllDigits = /[\d]+/;
    isDelemited = /^[\d\s\.\-]+/;
    value = $(this).val().trim();
    if (allowedPattern.test(value)) {
      value = value.replace(/[\s\.\-\(\)]+/g, "");
      if (isAllDigits.test(value) && ((_ref = value.length) === 7 || _ref === 10 || _ref === 11)) {
        return true;
      }
    }
    return false;
  };

}).call(this);
