// Generated by CoffeeScript 1.7.1
(function() {
  var $;

  $ = jQuery;

  $.fn.isValidAlphaNumericInput = function() {
    var allowedPattern, value;
    allowedPattern = /^[a-zA-z0-9\s]+$/i;
    value = $(this).val().trim();
    return allowedPattern.test(value);
  };

  $.fn.isValidEmailInput = function() {
    var allowedPattern, value;
    allowedPattern = /^[\w\-\_\.\d]+@\w+.\w{3}$/;
    value = $(this).val().trim();
    return allowedPattern.test(value);
  };

}).call(this);
